steps:
  # Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/pacc-raw-data/pacc-repo/pacc-workflow:latest', '.']
  
  # Push Docker Image lên Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/pacc-raw-data/pacc-repo/pacc-workflow:latest']

images:
  - 'asia-southeast1-docker.pkg.dev/pacc-raw-data/pacc-repo/pacc-workflow:latest'

options:
  logging: CLOUD_LOGGING_ONLY